config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#index"
  # get "/check", to: "users#check"

  resources :users, only: [:new, :create, :show]
  resources :gardens, only: [:new, :create, :show, :update]
  resources :plants, only: [:new, :create, :show, :update]

  get "signin", to: "sessions#new", as: "login"
  post "signin", to: "sessions#create"
  delete "signout", to: "sessions#destroy", as: "signout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  belongs_to :user
  has_many :plants, dependent: :destroy
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gardens
  has_many :plants, through: :gardens
  validates_uniqueness_of :email, :case_sensitive => false, :with => /.+@.+\..+/i
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :fetch_user

  private

  def fetch_user
    # user = session[:user_id]
    @current_user = User.find_by_id(session[:user_id])
  end

  def authenticate_user
    if @current_user.nil?
      flash[:error] = "Access denied"
      render json: {status: :unauthorized}
      redirect_to root_path
    end
  end

end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  
  def new
    @garden = Garden.new
  end

  def create
    if @current_user.present?
      garden = Garden.create(user_id: @current_user.id, width: params[:width], height: params[:height])
    end

    if garden.save
      render json: garden.id
    end
  end

  def update
    garden = Garden.find(params[:garden_id])
    garden.update_attributes(width: params[:width], height: params[:height])

    render json: {message: "success!"}
  end

  def show
  end

  private

  def clean_params
    params.require(:garden).permit(:name, :lon, :lat, :user_id, :width, :height, :img_src, :left, :top, :ratio)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    # url = "http://www.growstuff.org/photos.json"
    # url = "https://openfarm.cc/api/v1/crops?filter="
    # searchterm = "tomato"
    # response = HTTParty.get("#{url}#{searchterm}")
    # headers['Access-Control-Allow-Origin'] = '*'
    #
    # render json: {data: response}
  end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def new
  end

  def create
    plant = Plant.create(garden_id: params[:garden_id], name: params[:name], left: params[:left], top: params[:top], img_src: params[:img_src])

    if plant.save
      render json: plant.id
    end
  end

  def show
  end

  def update
    plant = Plant.find(params[:plant_id])
    plant.update_attributes(left: params[:left], top: params[:top])

    render json: {message: "Successful update"}
  end

  private

  def clean_params
    params.require[:plant].permit[:name, :garden_id, :left, :top, :img_src]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user.present?
      if user.authenticate(params[:password])
        # we have a real user
        session[:user_id] = user.id
        redirect_to root_path
      else
        render :new
      end
    else
      flash[:error] = "Wrong email address or password"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = "Successfully logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(clean_params)
    if @user.save
      session[:user_id] = @user.id
      respond_to do |format|
        format.html do
          redirect_to new_garden_path
        end
        format.json do
          render json: @user.id
        end
      end
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def clean_params
    params.require(:user).permit(:email, :name, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gardens/new.html.erb
<!-- <div class="container">
  <h2 class="header center green-text text-accent-3">Design your dream garden</h2>
</div> -->
<div>
  <div id="canvas">
    <div id="design-container"><div class="center"><button class="btn-large waves-effect waves-light green accent-3" id="start-button">Start Designing</button></div></div>
    <canvas id="garden-plan">
      <div id="message">
        <h4>Drop your plants here</h4>
      </div>
    </canvas>
  </div>
  <!-- <div id="planter">
    <div id="box">
      <h5 class="center">Planting Box</h5>
      <div id="dimension"></div>
      <% if @current_user.present? %>
        <div class="center">
          <button id="generate-list" class="btn waves-effect waves-light green accent-3">Generate Shopping List</button>
        </div>
      <% end %>
    </div>
  </div> -->

<!-- <div class="container"> -->
  <div id="planter">
    <div id="box">
      <div class="headline">
        <h5 class="left align"><i class="fa fa-leaf" aria-hidden="true"></i>Planting Box</h5>
      </div>
      <div id="dimension" class="left align"></div>
    </div>
    <ul class="collapsible" data-collapsible="accordion">
     <li>
       <div class="collapsible-header"><i class="material-icons">filter_drama</i>Garden Size</div>
       <div class="collapsible-body">
         <span>
           <p>Enter the dimensions of your garden here</p>
           <div class="input-field">
             <input type="text" id="width" placeholder="Enter in metres"/>
             <label for="width">Width</label>
           </div>
           <div class="input-field">
             <input type="text" id="height" placeholder="Enter in metres"/>
             <label for="height">Height</label>
           </div>
           <div class="input-field center">
             <button id="draw-canvas" class="btn waves-effect waves-light green accent-3">Create</button>
           </div>
         </span>
       </div>
     </li>
     <li>
       <div class="collapsible-header"><i class="material-icons">search</i>Search for a Plant</div>
       <div class="collapsible-body">
        <span>
          <p>Enter the plant name here</p>
          <div class="input-field">
            <input type="text" id="plant-name"/>
            <label for="plant-name">Name</label>
          </div>
          <div class="input-field center">
            <button id="plant-search" class="btn waves-effect waves-light green accent-3">Search</button>
          </div>
        </span>
      </div>
     </li>
     <li>
       <div class="collapsible-header"><i class="material-icons">whatshot</i>Search Results</div>
       <div class="collapsible-body">
        <span>
          <div id="plant-details"></div>
        </span>
      </div>
     </li>
     <!-- <li>
       <div class="collapsible-header" id="plant-box-collapsible"><i class="fa fa-leaf" aria-hidden="true"></i>Planting Box</div>
       <div class="collapsible-body">
         <div id="dimension"></div>
        <span>
          <div id="box"></div>
        </span>
      </div>
     </li> -->
   </ul>
 </div>
</div>

app/views/includes/_flash_notices.html.erb
<% if flash %>
  <% flash.each do |k,v| %>
    <div class="card grey lighten-2 <%= k.to_s %>" id="flash-notice">
      <i class="material-icons grey-text right close">close</i>
      <div class="card-content grey-text center">
        <h5><%= k.to_s.capitalize %></h5>
        <p><%= v %></p>
      </div>
    </div>
  <%end%>
  <% flash.clear %>
<%end%>

app/views/includes/_footer.html.erb
<footer class="page-footer grey lighten-1">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Garden Wizard</h5>
        <p class="grey-text text-lighten-4">Thyme to design and get your dream garden. We are here to help you create just that.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Site Map</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Create Us</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Privacy Policy</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2017 Copyright  Built by Hen Chow
    </div>
  </div>
</footer>

app/views/includes/_navigation.html.erb
<nav class="green accent-3" role="navigation">
  <div class="nav-wrapper container">
    <a href="/" class="brand-logo left"><i class="fa fa-pagelines" aria-hidden="true"></i>Garden Wizard</a>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <% if @current_user.present? %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Save", root_path %></li>
        <!-- <li><%= link_to "Generate List", root_path %></li> -->
        <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Create", new_garden_path %></li>
        <li><%= link_to "Sign In", signin_path %></li>
        <li><%= link_to "Sign Up", new_user_path %></li>
      <% end %>
    </ul>
    <ul id="nav-mobile" class="side-nav" style="transform: translateX(-100%);">
      <% if @current_user.present? %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Save", root_path %></li>
        <!-- <li><%= link_to "Generate List", root_path %></li> -->
        <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Create", new_garden_path %></li>
        <li><%= link_to "Sign In", signin_path %></li>
        <li><%= link_to "Sign Up", new_user_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Garden Wizard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= javascript_include_tag 'application' %>

  <% if @current_user.present? %>
    <script>
      var current_user = <%= @current_user.id %>
    </script>
  <% end %>
  </head>

  <body>
    <%= render "includes/navigation" %>
    <div class="container">
      <%= render "includes/flash_notices" %>
    </div>
    <%= yield %>
    <%= render "includes/footer" %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="content">
  <div id="spotlight">
    <div class="container">
      <br>
      <br>
      <h1 class="header center deep-purple-text text-darken-4">Time to Garden</h1>
      <div class="row center">
        <h5 class="header col s12 light">Create your own personalise gardening plan today</h5>
      </div>
      <div class="row center">
        <%= link_to "Get Started", new_garden_path, class: "btn-large waves-effect waves-light green accent-3" %>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center deep-purple-text"><i class="medium material-icons">description</i></h2>
            <h5 class="center">Garden dimensions</h5>

            <p class="light">Create your garden plan based on your personal specs.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center deep-purple-text"><i class="fa fa-leaf" aria-hidden="true" style="font-size: 1.25em"></i></h2>
            <h5 class="center">Pick the plants</h5>

            <p class="light">Search through our database to find the right plants for your garden.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center deep-purple-text"><i class="fa fa-arrows" aria-hidden="true" style="font-size: 1.25em"></i></h2>
            <h5 class="center">Arrange your plants</h5>

            <p class="light">Create and layout your plants to design a plan suited for your needs.</p>
          </div>
        </div>
      </div>
    </div>
    <br><br>
  </div>
  <div class="divider"></div>
  <div class="container"></div>
</div>

app/views/users/new.html.erb
<div class="container" id="sign-up">
  <div class="section">
    <div class="row">
    <%= form_for @user, html: {class: "col s12 center"} do |el| %>
      <div class="row">
        <div class="col s12 m4 l2"></div>
        <div class="input-field col s12 m4 l8">
          <i class="material-icons prefix">account_circle</i>
          <%= el.text_field :name, placeholder: "Name", id: "icon_prefix" %>
        </div>
        <div class="col s12 m4 l2"></div>
      </div>
      <div class="row">
        <div class="col s12 m4 l2"></div>
        <div class="input-field col s12 m4 l8">
          <i class="material-icons prefix">email</i>
          <%= el.text_field :email, placeholder: "Email", id: "icon_email" %>
        </div>
        <div class="col s12 m4 l2"></div>
      </div>
      <div class="row">
        <div class="col s12 m4 l2"></div>
        <div class="input-field col s12 m4 l8">
          <i class="material-icons prefix">vpn_key</i>
          <%= el.password_field :password, placeholder: "Password", id: "icon_password" %>
        </div>
        <div class="col s12 m4 l2"></div>
      </div>
      <div class="row">
        <div class="col s12 m4 l2"></div>
        <div class="input-field col s12 m4 l8">
          <%= el.submit "Sign Up", class: "btn waves-effect waves-light green accent-3" %>
        </div>
        <div class="col s12 m4 l2"></div>
      </div>
    <% end %>
    </div>
  </div>
</div>